# Copyright (c) 2023, NVIDIA CORPORATION.  All rights reserved.
#
# NVIDIA CORPORATION and its licensors retain all intellectual property
# and proprietary rights in and to this software, related documentation
# and any modifications thereto.  Any use, reproduction, disclosure or
# distribution of this software and related documentation without an express
# license agreement from NVIDIA CORPORATION is strictly prohibited.

Component:
  app-version: 0.0.1
  description: default description
  helmUrlLocationPath: https://helm.ngc.nvidia.com/myorg/myteam/charts
  name: pgadmin
  version: 0.0.1
affinity: {}
applicationSpecs:
  pgadmin-deployment:
    apptype: stateless
    containers:
      pgadmin-container:
        env:
        - name: PGADMIN_DEFAULT_EMAIL
          value: pgadmin4@pgadmin.org
        - name: PGADMIN_DEFAULT_PASSWORD
          value: admin
        - name: PGADMIN_CONFIG_SERVER_MODE
          value: 'False'
        image:
          pullPolicy: IfNotPresent
          repository: dpage/pgadmin4
          tag: 8.13.0
        ports:
        - containerPort: 80
          name: http
    services:
      pgadmin-service:
        ports:
        - name: http-api
          port: 5050
          targetPort: 80
defaultVolumeMounts:
- mountPath: /opt/workload-config
  name: workload-cm-volume
- mountPath: /opt/configs
  name: configs-volume
- mountPath: /opt/scripts
  name: scripts-cm-volume
defaultVolumes:
- configMap:
    name: pgadmin-workload-cm
  name: workload-cm-volume
- configMap:
    name: pgadmin-configs-cm
  name: configs-volume
- configMap:
    name: pgadmin-scripts-cm
  name: scripts-cm-volume
egress: {}
externalFiles: []
image:
  pullPolicy: IfNotPresent
imagePullSecrets: []
ingress:
  enabled: false
metrics: {}
nodeSelector: {}
podAnnotations: {}
podSecurityContext: {}
replicaCount: 1
resources: {}
securityContext: {}
storageClaims: {}
tolerations: []
workloadSpecs:
  dummy: {}



configs:
  config.yaml:
    SampleConfig:
      sampleValue: 0

